[package]
name = "rusttest"
version = "0.1.0"
authors = ["Ben Collier <bencollier@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { features = ["derive"]}
toml = "0.5.8"